spring:
  application:
    name: must-springboot2-mybatis-mysql
  thymeleaf:
    cache: false
  profiles: 
    active: dev
logging: 
  level: 
    root: INFO
  file: logs/logTest.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
server:
  port: 80
mybatis:
  configLocation: mybatis-config.xml
  mapperPackages: org.must.must.mapper